### ISSUE TITLE
Doesn't account for multiple hexes in a given decl

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/postcss-rgb-plz#1]
Found an edge case where this won't actually convert the value:

``` css
box-shadow: 0 0 10px #ffffff, 0 2px 3px #333333;
```

...will convert to...

``` css
box-shadow: 0 0 10px #ffffff, 0 2px 3px rgb( 51, 51, 51 );
```

...and that initial `#ffffff` won't get converted.

**Comment by ben-eb** [comment]
I suggest you use https://github.com/TrySound/postcss-value-parser to properly parse through the values. :smile:

**Comment by himynameisdave** [comment]
@ben-eb Very cool... so is that a standalone postcss plugin or just a tool to use in other plugins to make color parsing easier?

**Comment by ben-eb** [comment]
It's a tool for iterating over values that are CSS-like. You're looking to analyse `word` tokens for hex values. I used it here:

https://github.com/ben-eb/midas/blob/master/src/stringifier.js#L125-L131
